### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by OffsetMonkey538** [OffsetMonkey538/MonkeyConfig538#1]
- [ ] Add (de)serializers for some common minecraft classes
    - [ ] PotionEffectInstance
    - [ ] think of some more common things people would want to use in a config.
- [ ] Mod menu integration
- [ ] Documentation
    - [ ] Readme
    - [ ] Github Wiki
